version: '3.8'

services:
  gitissuer-api:
    build:
      context: .
      dockerfile: GitIssuer.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: gitissuer-api
    restart: unless-stopped